### PR TITLE
add expression language dependency

### PR DESCRIPTION
**Pull request by norkunas**

### CODE REVIEW

**Comment by rosstuck** [comment]
Awesome! Dumb question: can we rely on 2.7 stable instead of the 2.6 dev branch or is there something not yet covered there? Thanks again for this, much appreciated! :smile:

**Comment by norkunas** [comment]
Yes, we can. I tested at first with 2.7, but for consistency made version same as dependency injection component.

**Comment by norkunas** [comment]
Do I need to change also the DI version or you want that only for expression lang?

**Comment by rosstuck** [comment]
Might as well update too, if you don't mind :)

**Comment by rosstuck** [comment]
Thanks, will get this deployed later today

**Comment by norkunas** [comment]
Good :+1:

**Comment by rosstuck** [comment]
Done and live! You da man! :D

**Pull request merged**
